[package]
name = "tidal-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = "0.25.0"
rodio = { version = "0.20.1", default-features = false, features = ["symphonia-flac", "symphonia-aac", "symphonia-isomp4"] }
souvlaki = "0.8.2"
stream-download = { version = "0.20.0", features = ["reqwest-native-tls"] }
tokio = { version = "1.45.1", default-features = false, features = ["rt-multi-thread"] }
